definitions:
  inputs: &inputs
    xcode:
      description: Xcode version
      type: choice
      options: [27.2, 27.1, 27.0, 26.6, 26.5, 26.4, 26.3, 26.2, 26.1, 26.0, 16.4, 16.3, 16.2, 16.1, 16.0]
      default: 27.1
      
workflows:
  run-benchmark:
    inputs: *inputs
    environment:
      xcode: "${{ inputs.xcode }}"
    labels:
      - Xcode ${{ inputs.xcode }}
    scripts:
      - echo "Using Xcode ${{ inputs.xcode }}"
      - time sh benchmark.sh | tee /tmp/benchmark.log
      - script: cat /tmp/benchmark.log
        when:
          condition: true
    artifacts:
      - /tmp/benchmark.log

  run-benchmark-cache:
    inputs: *inputs
    environment:
      xcode: "${{ inputs.xcode }}"
    labels:
      - Xcode ${{ inputs.xcode }}
    cache:
      cache_paths:
        - /tmp/xcode-benchmark-compilation-cache
        - $HOME/Library/Developer/Xcode/DerivedData/CompilationCache.noindex
    scripts:
      - echo "Using Xcode ${{ inputs.xcode }}"
      - time sh benchmark-cache.sh > /tmp/benchmark.log
      - script: cat /tmp/benchmark.log
        when:
          condition: true
    artifacts:
      - /tmp/benchmark.log
